logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:sqlite:target/pargon-server.db
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

pargon:
  ffmpeg-path: target/bin/ffmpeg.exe
  ffprobe-path: target/bin/ffprobe.exe
